### ISSUE TITLE
Set Alias - The term 'Get-ChildItem-Color' is not recognized

### ISSUE THREAD

**Issue by davesbrown** [joonro/Get-ChildItem-Color#11]
ls : The term 'Get-ChildItem-Color' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ls
+ ~~
    + CategoryInfo          : ObjectNotFound: (Get-ChildItem-Color:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Windows 10
Used example to setup profile with Import and Set-Alias

**Comment by joonro** [comment]
Hi -

It seems the module is not installed - did you install the module with `Install-Module Get-ChildItemColor` (or `Install-Module Get-ChildItemColor -Scope CurrentUser`)?

**Comment by mikesigs** [comment]
It looks to me like you just have too many hyphens in the name. It should be `Get-ChildItemColor` not `Get-ChildItem-Color`.

**Comment by joonro** [comment]
Thank you very much for catching it!
