### ISSUE TITLE
Get-ChildItemColor directory isn't grey like Get-ChildItemColorFormatWide

### ISSUE THREAD

**Issue by jdheyburn** [joonro/Get-ChildItem-Color#14]
Love this feature first of all. Only a minor trivial point I had noticed:

The output of the Directory name in Get-ChildItemColor is the same colour as what the first item in the list is (i.e. yellow in the case of a directory being the first item). While for Get-ChildItemColorFormatWide is it grey. Is this by design?

**Comment by joonro** [comment]
Hi - 

Thanks for kind words. Yes that is an unfortunate by-product of just changing (`$Host.UI.RawUI.ForegroundColor`) before calling an `$item` in the loop. This way one can use pipe, but the directory is printed as a part of the `$item`, thus it shares the same color as the item.

I would love to have a more consistent color but I'm not sure if this is fixable. (Previously the script actually wrote file names manually and thus I could control it, but it did not allow the usage of pipe).

**Comment by reli-msft** [comment]
@joonro 
https://stackoverflow.com/questions/9406434/powershell-properly-coloring-get-childitem-output-once-and-for-all
Maybe helpful

**Comment by joonro** [comment]
@reli-msft Thanks a lot for this. It seems that code will fix this --- I currently do not have time to implement this so a PR will be appreciated.

**Comment by joonro** [comment]
Hi, 

I incorporated [PSColor](https://github.com/Davlind/PSColor)'s implementation, and it should be working now. Note that you can just use `Get-ChildItem`.
