### ISSUE TITLE
`Get-ChildItemColorFormatWide` error on PowerShell ISE

### ISSUE THREAD

**Issue by thorstenkampe** [joonro/Get-ChildItem-Color#15]
Error occurs only in PowerShell ISE:
```
Exception calling "Substring" with "2" argument(s): "Length cannot be less than zero.
Parameter name: length"
At C:\Users\thorsten\Documents\PowerShell\Modules\Get-ChildItemColor\1.2.1\Get-ChildItemColor.psm1:126 char:13
+             $toWrite = $toWrite.Substring(0, $pad - 3) + "..."
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
Error formatting a string: Input string was not in a correct format..
At C:\Users\thorsten\Documents\PowerShell\Modules\Get-ChildItemColor\1.2.1\Get-ChildItemColor.psm1:129 char:9
+         Write-Host ("{0,-$pad}" -f $toWrite) -Fore $Color -NoNewLine: ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({0,--1}:String) [], RuntimeException
    + FullyQualifiedErrorId : FormatError
[...]
```

**Comment by joonro** [comment]
Thanks for reporting. It seems it won't work in ISE - I will add comments on this.

**Comment by joonro** [comment]
By the way, did you import the module in your ISE profile? (`$Home\[My ]Documents\WindowsPowerShell\Microsoft.P owerShellISE_profile.ps1`) If you put these into your console profiles (`$Home\[My ]Documents\WindowsPowerShell\Profile.ps1`), it will not be used in ISE so it should be fine. (Please see https://blogs.technet.microsoft.com/heyscriptingguy/2012/05/21/understanding-the-six-powershell-profiles/ for different profile locations).

**Comment by joonro** [comment]
Resolved by c089a794bc5590ab5a478ed111b879d19d8cedfe.

**Comment by thorstenkampe** [comment]
I solved it like this:
```powershell
if ($Host.Name -eq 'Windows PowerShell ISE Host') {
    $_IsPowerShellISE = $true
}

if (-not $_IsPowerShellISE) {
    Set-Alias -Name ls                            `
              -Value Get-ChildItemColorFormatWide `
              -Option AllScope
}
```

**Comment by joonro** [comment]
Yes that works too but I'm not sure which is a better way to go (having a separate profile VS. conditions in a global profile). I have no idea what is the best practice. :) Thank you!

**Comment by joonro** [comment]
By the way, if you want to open a PR on the README file (with conditional statements that you described) I will be glad to accept it.
