### ISSUE TITLE
Minor: newlines differ between Get-ChildItemColor and Get-ChildItemColorWide

### ISSUE THREAD

**Issue by mattdkerr** [joonro/Get-ChildItem-Color#17]
Get-ChildItemColor has no empty newlines after the last row of output.
Get-ChildItemColorWide has two empty newlines after the last row of output.

Ideally they should both be 1 empty newline.

tested with version 1.2.1

**Comment by joonro** [comment]
Hi - 

I'm very sorry for the late reply. In my machine, I'm actually getting two empty lines with `Get-ChildItemColor`, and only one empty line with `Get-ChildItemColorFormatWide`. Could you please actually provide a screenshot of what is going on? Thank you!

![2018-10-29 22_32_47-posh git get-childitemcolor master](https://user-images.githubusercontent.com/1063143/47694189-9f763100-dbca-11e8-8321-c726c2e1ead6.png)

**Comment by musm** [comment]
can you fix this by adding only one new line?

**Comment by joonro** [comment]
Hi,

Sorry about late reply. I misunderstood the issue @mattdkerr reported. The inconsistent newline behavior after the last row should be fixed now.
