### ISSUE TITLE
Broken output from Select-String -Context

### ISSUE THREAD

**Issue by marcinsmialek** [joonro/Get-ChildItem-Color#26]
When using Get-ChildItemColor, the default console text output from Select-String doesn't show the captured context. Also, it shouldn't display the file name if the input is stream.
Importing module with -NoClobber seems to fix this issue, but it also disables general coloring.

Test:
`1, 2 | Select-String 1 -Context 1`

Expected:
```
> 1
  2
```

Actual:
`InputStream:1:1`

**Comment by joonro** [comment]
Hi, sorry for the late response. This should be fixed now with v3.0.0 (d651f922462d98934c1beff565c931bbbb80d39e) --- I just tested and got the expected results.
