### ISSUE TITLE
Display issue with Chinese

### ISSUE THREAD

**Issue by zl3one6** [joonro/Get-ChildItem-Color#27]
Hi, thanks for developing such an awesome script. I didn't test for other languages, but when files name with English and Chinese, the output of `ls` will be disordered. Hope this can be fixed later.
![Snipaste_2019-08-11_16-22-30](https://user-images.githubusercontent.com/14806942/62831625-1dd12a80-bc55-11e9-860c-a83b8b5b67f3.jpg)

**Comment by joonro** [comment]
Hi-

I cannot reproduce this as it is working in my machine (see the screenshot below). Are you using the latest version?

![image](https://user-images.githubusercontent.com/1063143/63041404-6ecb6380-be8d-11e9-8e19-aef36c0133f1.png)

**Comment by joonro** [comment]
Oops you meant they are not ordered correctly? With a quick look, I actually could not see what you are talking about --- could you please elaborate?

**Comment by zl3one6** [comment]
Yes, I use the latest version. I think I didn't explain the issue correctly. I test a kind of scenario that there are a lot of folders with English name and Chinese name, and a lot of English name and Chinese name files. The picture shows the name of the folders and files are not aligned.
![Uploading Snipaste_2019-08-16_16-26-56.jpg…]()

**Comment by zl3one6** [comment]
Yes, I use the latest version. I think I didn't explain the issue correctly. I test a kind of scenario that there are a lot of folders with English name and Chinese name, and a lot of English name and Chinese name files. The picture shows the name of the folders and files are not aligned.
![Snipaste_2019-08-16_16-26-56](https://user-images.githubusercontent.com/14806942/63155209-b6e0b680-c044-11e9-81b7-02156b790792.jpg)

**Comment by joonro** [comment]
Oh I understand --- thanks for the elaboration. I think it must be that the character length calculation in `Get-ChildItemColorFormatWide` is broken for unicode characters, since I see this with Korean characters as well. Let me see if I can fix this quickly.

**Comment by joonro** [comment]
It does not look like it would be easy to fix. The issue is for these characters, `.Length` method returns the character length, but in printing, these characters takes 2 spaces instead of 1. For example,

```
> "한글파일".Length
4
```

I will get back to this when I have more time. Sorry!

**Comment by zl3one6** [comment]
That's great. Looking forward to the fix. Thanks!

**Comment by reli-msft** [comment]
@joonro 
You may need something _like_ `wcwidth`. A reference could be this: https://github.com/timoxley/wcwidth

**Comment by joonro** [comment]
This is fixed thanks to @shiena.
