### ISSUE TITLE
Fails inside OneDrive

### ISSUE THREAD

**Issue by liquidtoon01** [joonro/Get-ChildItem-Color#28]
Hi, it seems to fail if you navigate to OneDrive folders, it just keeps the default color scheme?

**Comment by liquidtoon01** [comment]
Seems to be due to them being 'symlinks':

$GetChildItemColorTable.File.Add('Symlink', "Cyan")

**Comment by joonro** [comment]
Hi, sorry for the late response and thank you for the pointer. I will take a look.

**Comment by joonro** [comment]
Fix with b907185fc12fd35ae2384b2f1cc13e65126faac1.
