### ISSUE TITLE
Is it possible to get an `ll` equivalent?

### ISSUE THREAD

**Issue by ransagy** [joonro/Get-ChildItem-Color#30]
I've been wanting to make my linux shells and (windows) powershell core shells look as similar as possible and this module is the first thing that pops up on every search combo i tried - Just shows you how useful this library is, so thanks :]

One thing I'm missing and wasn't entirely sure i understood if possible or not from the README - Is it possible to get an `ll` equivalent? i.e. like the wide example, just with coloring only on the Name property rather than all the others.

**Comment by joonro** [comment]
Hey I'm sorry for the (way) late reply - and thanks for the kind words. Could you please provide an example of `ll`?

**Comment by ransagy** [comment]
Trying to remember from what i wrote and the README page; i think what i meant was that currently the entire row is colored - so the Mode, LastWriteTime, etc columns, rather than just the Name column - which is how the default `ll` alias in bash looks like:

![image](https://user-images.githubusercontent.com/6785058/163455657-c6817084-14c3-4c99-af1c-05c72a879c97.png)

**Comment by joonro** [comment]
I see --- thanks for providing the example. I haven't looked at the code for a while, but this doesn't look like can be done with a quick fix. Will keep this in mind though, thank you again.

**Comment by joonro** [comment]
Actually it was pretty easy to implement. Resolved in 841d0178ddb04a4b0c75bd5accc3523ecc7765d9.
