### ISSUE TITLE
Out-Default function breaks $?

### ISSUE THREAD

**Issue by chenxiaolong** [joonro/Get-ChildItem-Color#31]
The definition of `Out-Default` seems to be breaking the usage of `$?`.

For example, if I run an invalid command in `pwsh -noprofile`, I get this:
```
PS C:\Users\chenxiaolong> git asdf
git: 'asdf' is not a git command. See 'git --help'.

The most similar command is
        add
PS C:\Users\chenxiaolong> echo $?
False
```

If I import `Get-ChildItemColor` (version `2.1.1`), then `$?` stops working properly:
```
PS C:\Users\chenxiaolong> Import-Module Get-ChildItemColor
PS C:\Users\chenxiaolong> git asdf
git: 'asdf' is not a git command. See 'git --help'.

The most similar command is
        add
PS C:\Users\chenxiaolong> echo $?
True
```

If I remove the `Out-Default` function, then things work again, but of course, no more `ls` colors:
```
PS C:\Users\chenxiaolong> Remove-Item Function:Out-Default
PS C:\Users\chenxiaolong> git asdf
git: 'asdf' is not a git command. See 'git --help'.

The most similar command is
        add
PS C:\Users\chenxiaolong> echo $?
False
```

**Comment by schmjop** [comment]
I have the same issue unfortunately. @joonro is there as possible workaround?

**Comment by vdsbenoit** [comment]
I think it is related to [an issue in PSColor](https://github.com/Davlind/PSColor/issues/23), which Get-ChildItemColor relies on. Both projects seem to be unmaintained so I don't think this issue is going to be resolved anytime soon.

**Comment by joonro** [comment]
Hi, sorry for the late response. I'm glad to let you know that I was able to fix this issue (d651f922462d98934c1beff565c931bbbb80d39e). Now this module no longer overloads `Out-Default` --- instead, users should use `Get-ChildItemColor`. The function is now pipeline-aware (i.e., it does not touch the output when used as a part of a pipeline) and I think it should be more robust. Please let me know if this works for you.

**Comment by joonro** [comment]
I will close this as this should be resolved in the latest version. Please feel free to open it again if there is still an issue.

**Comment by vdsbenoit** [comment]
I confirm it's fixed on my side too! Thank you so much

**Comment by joonro** [comment]
Great! Sorry it took so long to fix, but better late than never I guess :)

**Comment by vdsbenoit** [comment]
Sure! Thank you for maintaining this project, which is quite handy
