### ISSUE TITLE
incorrect  spacing after first launch

### ISSUE THREAD

**Issue by musm** [joonro/Get-ChildItem-Color#36]
![image](https://user-images.githubusercontent.com/4319522/78289370-17e3ce80-74f0-11ea-8b7c-d0d3a9d1af9b.png)
![image](https://user-images.githubusercontent.com/4319522/78289399-2631ea80-74f0-11ea-8c9c-6ac6507950f5.png)

first time to execute we see no space after the directory list. The second time we see a blank space.

@joonro

**Comment by alanlivio** [comment]
I find the same problem. Is there a solution?

**Comment by alanlivio** [comment]
@musm it was answered in https://github.com/gerardog/gsudo/issues/77
