### ISSUE TITLE
Feature Req: Show trailing slash for directory names in wide format view

### ISSUE THREAD

**Issue by saumyajyoti** [joonro/Get-ChildItem-Color#37]
Please add "\\" at the end of directory name in wide format list.

**Comment by joonro** [comment]
Hi, sorry for the late response. This is easy to do, but could you please add more context for this? I don't think I have seen this before.

**Comment by saumyajyoti** [comment]
Hi,
Actually this is more like the output of linux "ls" command where the directory name is shown as "dirname/"

**Comment by joonro** [comment]
Implemented by f02bd345a6af715b82b7477c90ac4c1594c4ea67.

**Comment by saumyajyoti** [comment]
Thanks
