### ISSUE TITLE
[req] Diferent colors for hard and softlinks plz (especialyhardlinks)

### ISSUE THREAD

**Issue by NicTanghe** [joonro/Get-ChildItem-Color#39]
Plz make hard and softlinks a diferent color preferably red.

**Comment by joonro** [comment]
Hi, sorry about late response. Symlinks are being treated differently, currently it is set to `Cyan` by default ([source link](https://github.com/joonro/Get-ChildItemColor/blob/develop/src/Get-ChildItemColorTable.ps1#L172)). You can easily change this to Red by:

```powershell
$GetChildItemColorTable.File['Symlink']= "Red"
```
