### ISSUE TITLE
How to customize the color and save it for next use?

### ISSUE THREAD

**Issue by ZmdnaHF0ZmFqYXZ0O** [joonro/Get-ChildItem-Color#40]
Hi,
How to customize the color (use Hex Color Code or RGB(x.y.z)) and save it for next use?
Thx!

**Comment by joonro** [comment]
Hi,

You can use a limited set of color names (Black, DarkBlue, DarkGreen, Cyan, etc) in customization. Note that actual colors for those names are customizable. So what you can do is having `$GetChildItemColorTable.File['Directory'] = "Blue"` for example, and then use your desired color as `Blue` in whatever terminal program (ConEmu, Windows Terminal, etc) that you use. For example, see https://github.com/joonro/ConEmu-Color-Themes.

**Comment by ZmdnaHF0ZmFqYXZ0O** [comment]
Thank you!
