### ISSUE TITLE
Directory and column descriptions only show up on first launch

### ISSUE THREAD

**Issue by LucasOe** [joonro/Get-ChildItem-Color#41]
The "Directory" and the "Mode", "LastWriteTime", "Length" and "Name" text only show up on the first launch of Get-ChildItemColor in the directory. After chaning the dir the headline text shows up again. This doesn't happen with Get-ChildItemColorFormatWide
[](url)
![Cmder](https://user-images.githubusercontent.com/16548335/89798470-83881900-db2c-11ea-8248-b0e8d53aa60a.png)

**Comment by joonro** [comment]
Hi sorry for the late response and thank you for reporting this --- I quickly checked the code and there is no difference between the first and and the second, so it is is quite an odd behavior. Will keep this in mind.

**Comment by LucasOe** [comment]
After looking at it again I noticed this is semi intended behaviour. The directory only gets printed if the parent directory has changed since the last call. [LastParentName has to be not equal to ParentName](https://github.com/joonro/Get-ChildItemColor/blob/a8bdcfc636daf501183466e9597b32cd46b021ab/src/FileInfo.ps1#L35). Removing the if clause prints the directory before every single file however.

**Comment by joonro** [comment]
I see, thank you for the pointer --- I forgot about doing this. Yes this doesn't make sense, I should remove this.

**Comment by joonro** [comment]
Fixed with 78ab2025318effafc6eed526450fd69523fef6d7.
