### ISSUE TITLE
Version 2.2.1 not uploaded to PowerShell Gallery

### ISSUE THREAD

**Issue by yodaldevoid** [joonro/Get-ChildItem-Color#45]
Version 2.2.1 was released 14 days ago (thank you to those who contributed and to @joonro for taking a little time to make a new release!), but this release was not pushed to PowerShell Gallery.

When you have time, please upload this version to PowerShell Gallery.

**Comment by joonro** [comment]
Thank you for the ping! I just published the module to PowerShell Gallery (https://www.powershellgallery.com/packages/Get-ChildItemColor/2.2.1)
