### ISSUE TITLE
How to support other file extensions like Office files extensions .pptx, .docx, .xlsx?

### ISSUE THREAD

**Issue by wenijinew** [joonro/Get-ChildItem-Color#46]
I tried to run below command and it fails. 

$GetChildItemColorExtensions.Add(
    'ExecutableList',
    @(
        ".docx",
        ".pptx",
        ".xlsx"
    )
)

**Comment by joonro** [comment]
Hi, can you provide the error message? 

(Btw, there are two dots before docx.)

**Comment by wenijinew** [comment]
```
Exception calling "Add" with "2" argument (s): "The item has already been added. Key in the lookup list: ExecutableList. Key added: ExecutableList."
At line: 1 char: 1
+ $ GetChildItemColorExtensions.Add (
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo: NotSpecified: (:) [], MethodInvocationException
     + FullyQualifiedErrorId: ArgumentException
```
I tried `$GetChildItemColorTable.File['.pptx'] = "Green"` and it works.

**Comment by joonro** [comment]
Ahh this is because arrays in PowerShell are immutable (https://stackoverflow.com/questions/70901754/powershell-append-objects-to-variable-list). What you can do is using `+=` operator.Note that you have to re-assign colors for the newly added extensions.

```
$GetChildItemColorExtensions['ExecutableList'] += @(
    ".docx",
    ".pptx",
    ".xlsx"
)

ForEach ($Extension in $GetChildItemColorExtensions['ExecutableList']) {
    $GetChildItemColorTable.File.Add($Extension, "Green")
}

```

In this case it seems like you want to have a new category, so in this case it would be easier to just create a new list:

```
$GetChildItemColorExtensions['OfficeList'] = @(
    ".docx",
    ".pptx",
    ".xlsx"
)

ForEach ($Extension in $GetChildItemColorExtensions['OfficeList']) {
    $GetChildItemColorTable.File.Add($Extension, "Green")
}

```

**Comment by joonro** [comment]
Added instructions (2b29e6c54addd12c57a818072be558cc03813e1a)
