### ISSUE TITLE
Unable to find type [uint] on Windows PowerShell 5

### ISSUE THREAD

**Issue by SnailNail** [joonro/Get-ChildItem-Color#47]
Running version 3.2.1 of `Get-ChildItemColor` command in Windows Powershell 5.1 results in the following error:
```powershell
PS C:\ > Get-ChildItemColor
Unable to find type [uint].
At C:\Program Files\WindowsPowerShell\Modules\get-childitemcolor\3.2.1\Get-ChildItemColor.psm1:231 char:5
+     [uint]
+     ~~~~~~
    + CategoryInfo          : InvalidOperation: (uint:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

Replacing the referenced `[uint]` with `[UInt32]` in Get-ChildItemColor.psm1 allows the script run.

According to the documentation, `[uint]`  and `[UInt32]` are both defined as accelerators for `[System.UInt32]` in [PowerShell Core](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_type_accelerators?view=powershell-7.2), but only `[UInt32]` is defined in [Windows PowerShell 5.1](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_type_accelerators?view=powershell-5.1).

**Comment by joonro** [comment]
Thanks for letting me know --- it seems like `uint` is just [an alias of](https://stackoverflow.com/a/2071175/439325) `uint32`, so I replaced the former with the latter (bbefbb9fa366a23d9c22afbe4eed399110717976). Please use the latest version (v3.2.2).
