### ISSUE TITLE
Unable to use grep when overriding ls with Set-Alias

### ISSUE THREAD

**Issue by talaniz** [joonro/Get-ChildItem-Color#5]
After implementing the script, I'm no longer able to pipe to `grep`. Instead, the `ls` command will list the entire directory structure. Current work around is to use the `Get-ChildItem` cmdlet instead. 

Example--

```
(Elevated) talaniz@OZL-TONY : ~\test : 8/26/2016 4:17:51 PM :
> ls

    Directory: C:\Users\talaniz\test

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        11/17/2013   9:47 PM        380 .project
-a---        11/17/2013  10:00 PM       1300 index.html

(Elevated) talaniz@OZL-TONY : ~\test : 8/26/2016 4:17:52 PM :
> ls | grep index

    Directory: C:\Users\talaniz\test

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        11/17/2013   9:47 PM        380 .project
-a---        11/17/2013  10:00 PM       1300 index.html
```

**Comment by joonro** [comment]
Thanks for reporting this. I will look into it.

**Comment by joonro** [comment]
I'm sorry, I don't think I will be able to fix this one at my current knowledge level of PowerShell.

**Comment by joonro** [comment]
Actually, I changed how the coloring is done completely the new version (1.0.0), so it now should work with piplelines. Sorry it took so long to fix this.
