### ISSUE TITLE
actual PowerShell have alredy coloring itself

### ISSUE THREAD

**Issue by theuserbl** [joonro/Get-ChildItem-Color#50]
I have had used PowerShell 7.1.4 before. And that have no coloring  of Get-ChildItem.

But now I have tried out the actual PowerShell 7.3.0-preview.5. And that have a coloring for the exe-files, the directories, *.zip files, ps1 files, psm1 files, psd1 files and possible other.

dll files, txt files, etc. are there non colored. Who that wants needing possibly still Get-ChildItemColor. But for all other is coloring in the original Get-ChildItem already included.

**Comment by theuserbl** [comment]
I currently see, that the coloring of Get-ChildItem is much bader then that of Get-ChildItemColor.
Get-ChildItem uses now the ANSI escape code.
That ends up, that a `dir | ogv` have the directory "Downloads" listed as "[44;1mDownloads[0m".
Similar with all colored files.

**Comment by joonro** [comment]
Hi sorry for the late reply. Thanks for letting me know, I'm glad that Powershell now has an ability color things. I actually didn't quite understand what you meant, it seems like unfortunately the Powershell coloring is causing problems when you do `dir | ogv`?

**Comment by joonro** [comment]
Anyway, I will close this, because this is not an issue --- if PowerShell natively supports coloring, I think that would be better than using this module anyway :)
