### ISSUE TITLE
[FeatureReq] '-Directory' and '-File' option for Get-ChildItemColorFormatWide

### ISSUE THREAD

**Issue by aniketgm** [joonro/Get-ChildItem-Color#53]
**Description**

As the title says, can we have the `-Directory` and `-File` option for Get-ChildItemColorFormatWide as well.

**Comment by joonro** [comment]
Hi sorry for the late reply, could you please briefly describe what those switches do?

**Comment by aniketgm** [comment]
Hello, as their name suggests, the `-Directory` and `-File` switches display *only directories* and *only files*, respectively.

![image](https://github.com/user-attachments/assets/827b72ff-9c53-4d7b-a744-76e6f6f298a6)

**Comment by joonro** [comment]
Ah sorry, I misread your initial comment. We already have this, you asked if we can add it to Get-ChildItemColorFormatWide. Got it, thanks for the clarification.

**Comment by joonro** [comment]
I just implemented this and created a new release. Thanks!
