### ISSUE TITLE
Issue when attempting to use in PSDrives

### ISSUE THREAD

**Issue by ryandcoates** [joonro/Get-ChildItem-Color#6]
Added this to my profile and updated my alias list for day to day use

seems to work as expected in folders but PSDrives return odd errors
I switched to WSMAN: to get this one as it only has one item to return
Useful.ps1 is a file I dot source in my profile to bring in a bunch of functions (including this one)

Index operation failed; the array index evaluated to null.
At C:\Data\PSRoot\Useful.ps1:67 char:13
-             $c = $color_table[$_.Extension]
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : NullArrayIndex

You cannot call a method on a null-valued expression.
At C:\Data\PSRoot\Useful.ps1:111 char:13
-             Write-Host ("{0,-7} {1,25} {2,10} {3}" -f $_.mode,
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by lrech** [comment]
Found the same error as reported by Ryan by simply performing a 'ls' or 'dir' on env:
Eg:

```
(Elevated) D:\Projects :
$ > ls env:
Index operation failed; the array index evaluated to null.
At Y:\My Documents\WindowsPowerShell\Get-ChildItem-Color\Get-ChildItem-Color.ps1:67 char:13
+             $c = $color_table[$_.Extension]
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

You cannot call a method on a null-valued expression.
At Y:\My Documents\WindowsPowerShell\Get-ChildItem-Color\Get-ChildItem-Color.ps1:111 char:13
+             Write-Host ("{0,-7} {1,25} {2,10} {3}" -f $_.mode,
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

```

**Comment by joonro** [comment]
Thanks for reporting this. I will look into it.

**Comment by joonro** [comment]
I changed the code so it now just returns `Get-Childitem` results for `DictionaryEntry` cases. Please let me know if this does not work for you.
